export const DAMO_BETAS: Record<string, { beta: number; label: string }> = {
  software: { beta: 1.25, label: "Software (SaaS / IT Services)" },
  tech_hardware: { beta: 1.18, label: "Technology Hardware" },
  telecom: { beta: 0.79, label: "Telecom" },
  oil_gas: { beta: 0.93, label: "Oil & Gas (Integrated)" },
  oil_prod: { beta: 1.08, label: "Oil & Gas (Production)" },
  retail: { beta: 0.85, label: "Retail (General)" },
  retail_online: { beta: 1.05, label: "Retail (Online)" },
  pharma: { beta: 0.78, label: "Pharmaceuticals" },
  healthcare: { beta: 0.79, label: "Healthcare" },
  banks: { beta: 0.58, label: "Banks" },
  insurance: { beta: 0.68, label: "Insurance" },
  realestate: { beta: 0.72, label: "Real Estate (REIT)" },
  utilities: { beta: 0.41, label: "Utilities" },
  auto: { beta: 1.05, label: "Automotive" },
  metals: { beta: 1.12, label: "Metals & Mining" },
  chemicals: { beta: 0.98, label: "Chemicals" },
  industrials: { beta: 1.02, label: "Industrials / Capital Goods" },
  transport: { beta: 0.87, label: "Transportation" },
  media: { beta: 0.99, label: "Media / Entertainment" },
  consumer: { beta: 0.63, label: "Consumer Staples" },
  fmcg: { beta: 0.7, label: "FMCG / Beverages" },
  conglomerate: { beta: 0.88, label: "Conglomerate / Diversified" },
};

export const COUNTRY_DATA: Record<string, { rfr: number; crp: number; erp: number; label: string }> = {
  usa: { rfr: 4.2, crp: 0.0, erp: 4.6, label: "United States" },
  india: { rfr: 7.1, crp: 2.0, erp: 4.6, label: "India" },
  china: { rfr: 2.8, crp: 1.5, erp: 4.6, label: "China" },
  uk: { rfr: 4.1, crp: 0.5, erp: 4.6, label: "United Kingdom" },
  germany: { rfr: 2.5, crp: 0.0, erp: 4.6, label: "Germany" },
  france: { rfr: 2.7, crp: 0.5, erp: 4.6, label: "France" },
  japan: { rfr: 0.9, crp: 0.5, erp: 4.6, label: "Japan" },
  brazil: { rfr: 10.5, crp: 2.5, erp: 4.6, label: "Brazil" },
  canada: { rfr: 3.8, crp: 0.0, erp: 4.6, label: "Canada" },
  australia: { rfr: 4.3, crp: 0.0, erp: 4.6, label: "Australia" },
  singapore: { rfr: 3.1, crp: 0.0, erp: 4.6, label: "Singapore" },
  uae: { rfr: 4.9, crp: 0.5, erp: 4.6, label: "UAE" },
  south_korea: { rfr: 3.4, crp: 0.5, erp: 4.6, label: "South Korea" },
};

export const PRECEDENTS = [
  { deal: "Microsoft / Activision Blizzard", yr: 2023, sector: "tech", val: 68.7, evEv: 26.8, evRev: 7.2, prem: 45, type: "Strategic" },
  { deal: "Broadcom / VMware", yr: 2023, sector: "tech", val: 61.0, evEv: 22.1, evRev: 5.8, prem: 44, type: "Strategic" },
  { deal: "Adobe / Figma (lapsed)", yr: 2023, sector: "tech", val: 20.0, evEv: null, evRev: 50.0, prem: 55, type: "Strategic" },
  { deal: "Oracle / Cerner", yr: 2022, sector: "tech", val: 28.3, evEv: 18.5, evRev: 5.1, prem: 20, type: "Strategic" },
  { deal: "Salesforce / Slack", yr: 2021, sector: "tech", val: 27.7, evEv: null, evRev: 26.0, prem: 55, type: "Strategic" },
  { deal: "NVIDIA / Arm (lapsed)", yr: 2022, sector: "tech", val: 40.0, evEv: null, evRev: 35.0, prem: 85, type: "Strategic" },
  { deal: "SAP / Qualtrics", yr: 2019, sector: "tech", val: 8.0, evEv: null, evRev: 20.0, prem: null, type: "Strategic" },
  { deal: "T-Mobile / Sprint", yr: 2020, sector: "telecom", val: 26.5, evEv: 8.2, evRev: 1.8, prem: 22, type: "Strategic" },
  { deal: "Verizon / Tracfone", yr: 2021, sector: "telecom", val: 6.25, evEv: 6.5, evRev: 1.2, prem: null, type: "Strategic" },
  { deal: "Vodafone / Idea (India merger)", yr: 2018, sector: "telecom", val: 23.0, evEv: 5.9, evRev: 2.1, prem: null, type: "Merger" },
  { deal: "Reliance / Future Retail", yr: 2022, sector: "retail", val: 3.4, evEv: 7.8, evRev: 0.9, prem: null, type: "Strategic" },
  { deal: "Amazon / Whole Foods", yr: 2017, sector: "retail", val: 13.7, evEv: 13.4, evRev: 0.8, prem: 27, type: "Strategic" },
  { deal: "Walmart / Flipkart", yr: 2018, sector: "retail", val: 16.0, evEv: null, evRev: 3.2, prem: null, type: "Strategic" },
  { deal: "ExxonMobil / Pioneer", yr: 2023, sector: "energy", val: 59.5, evEv: 9.8, evRev: 3.8, prem: 18, type: "Strategic" },
  { deal: "Chevron / Hess", yr: 2023, sector: "energy", val: 53.0, evEv: 10.2, evRev: 4.1, prem: 10, type: "Strategic" },
  { deal: "ConocoPhillips / Concho", yr: 2021, sector: "energy", val: 9.7, evEv: 8.9, evRev: 3.2, prem: 15, type: "Strategic" },
  { deal: "ONGC / HPCL (India)", yr: 2018, sector: "energy", val: 5.7, evEv: 4.5, evRev: 0.3, prem: 27, type: "Strategic" },
  { deal: "AbbVie / Allergan", yr: 2020, sector: "pharma", val: 63.0, evEv: 12.8, evRev: 3.6, prem: 45, type: "Strategic" },
  { deal: "Bristol-Myers / Celgene", yr: 2019, sector: "pharma", val: 74.0, evEv: 16.2, evRev: 4.9, prem: 54, type: "Strategic" },
  { deal: "Pfizer / Array BioPharma", yr: 2019, sector: "pharma", val: 10.64, evEv: null, evRev: 28.0, prem: 62, type: "Strategic" },
  { deal: "Sun Pharma / Taro (India)", yr: 2018, sector: "pharma", val: 0.38, evEv: null, evRev: null, prem: 20, type: "Strategic" },
  { deal: "HDFC Bank / HDFC Ltd (India)", yr: 2023, sector: "finance", val: 40.0, evEv: null, evRev: null, prem: null, type: "Merger" },
  { deal: "LTI / Mindtree (India)", yr: 2022, sector: "tech", val: 3.0, evEv: 28.0, evRev: 5.5, prem: 30, type: "Strategic" },
];
